### ISSUE TITLE
Wish: Add docs for API Gateway stage and deploy commands

### ISSUE THREAD

**Issue by markstos** [u-minor/aglex#3]
Version 0.2.0 added support 'stages' and 'deploy' subcommands for apigateway. It would be helpful if these were documented in the quick guide in the README. 

Thank you.

**Comment by u-minor** [comment]
I'll update README in a few days.
Thank you!

**Comment by u-minor** [comment]
https://github.com/u-minor/aglex/commit/6b7e1f12cb9c40ce768074e53600bde2491998fd

updated README and released new version.
